---
title: "p8105_hw2_sl5009"
author: "Shengzhi Luo"
date: "08/10/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,message=FALSE}
library(tidyverse)
library(readxl)
library(dplyr)
```

## Prolem 1
Read and clean the Mr.Trash Wheel sheet
```{r,message=FALSE}
Mr_Trash_Wheel<-read_excel("./Trash-Wheel-Collection-Totals-7-2020-2.xlsx")
Mr_Trash_Wheel=janitor::clean_names(Mr_Trash_Wheel)
```

```{r,results=FALSE}
drop_na(Mr_Trash_Wheel,dumpster)
```

```{r,results=FALSE}
round(Mr_Trash_Wheel$sports_balls,digits = 0)
```

Read and clean precipitation data for 2018 and 2019
```{r,message=FALSE}
Pre_2018=
  read_excel("./Trash-Wheel-Collection-Totals-7-2020-2.xlsx",sheet="2018 Precipitation")%>%
  janitor::clean_names()%>%
  drop_na()%>%
  mutate(
    year=2018
    )
Pre_2018=Pre_2018[-1,]
```

```{r,message=FALSE}
Pre_2019=
  read_excel("./Trash-Wheel-Collection-Totals-7-2020-2.xlsx",sheet="2019 Precipitation")%>%
  janitor::clean_names()%>%
  drop_na()%>%
  mutate(year=2019)
Pre_2019=Pre_2019[-1,]
```

```{r}
Pre_2018_2019=
  bind_rows(Pre_2018,Pre_2019) %>%
  mutate(
    precipitation_in=month.name[as.numeric(precipitation_in)]
  )
Pre_2018_2019
```




## Problem 2
```{r}
pols_month=
  read.csv("./fivethirtyeight_datasets/pols-month.csv")%>%
  separate(mon,into=c("year","month","day"))%>%
  mutate(
    president=prez_gop+prez_dem,
    month = month.abb[as.numeric(month)],
    year=as.numeric(year))%>%
  select(-c("prez_gop","prez_dem","day"))
```



```{r}
snp=
  read.csv("./fivethirtyeight_datasets/snp.csv")%>%
  separate(date,into=c("month","day","year"))%>%
  arrange(as.numeric(month))%>%
  mutate(
    month = month.abb[as.numeric(month)]
    )%>%
  select(-c("day"))%>%
  relocate(year,month,close)%>%
  mutate(
    year=as.numeric(year),
    year=ifelse(year>47, 1900+year, 2000+year)
  )%>%
  arrange(year)
```

```{r}
unemployment=
  read.csv("./fivethirtyeight_datasets/unemployment.csv")%>%
  pivot_longer(
    Jan:Dec,
    names_to="month",
    values_to = "unemployment rate"
  )
colnames(unemployment) <- c("year","month","unemployment rate")
```

```{r}
fas_data=
  left_join(pols_month,snp,by=c("year","month"))
res_data=
  left_join(fas_data,unemployment,by=c("year","month"))
res_data
```
## Problem 3

```{r}
Popular_Baby_Names<-read.csv("./Popular_Baby_Names.csv")
 
```


